version: "3.7"
services:
  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - ./volumes/ddclient/config:/config
    restart: unless-stopped
  hello_world:
    image: nginxdemos/hello
    ports:
      - 80:80
