apiVersion: v1
kind: Namespace
metadata:
  name:  minecraft
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-data-pvc
  namespace: minecraft
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-data
  namespace: minecraft
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    # Edit this to be an actual path on your server's filesystem
    path: /mnt/local-volumes/minecraft
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mimir # Edit this to be an actual kubernetes name of your server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data-pvc
      containers:
      - name: minecraft-server
        image: itzg/minecraft-server:latest
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1.5Gi
        env:
          - name:  EULA
            value: 'TRUE'
          - name: MODE
            value: creative
          - name: MOTD
            value: "You can't take the sky from me."
          - name: ALLOW_FLIGHT
            value: 'TRUE'
          - name: SERVER_NAME
            value: Fluffy Samurai
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
          - name: minecraft-data
            mountPath:  /data
        readinessProbe:
          exec:
            command:
            - mcstatus
            - 127.0.0.1
            - ping
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          exec:
            command:
            - mcstatus
            - 127.0.0.1
            - ping
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  type: NodePort
  ports:
    - port: 25565
      nodePort: 31000
  selector:
    app: minecraft-server
