apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-server
  namespace: hello-world
  labels:
    app: hello-world-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-server
  template:
    metadata:
      labels:
        app: hello-world-server
    spec:
      containers:
      - name: hello-world-server
        image: nginxdemos/hello:latest
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 1Gi
        ports:
        - containerPort: 80
          name: hello-world
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-server
  namespace: hello-world
  labels:
    app: hello-world-server
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 31000
  selector:
    app: hello-world-server
